# Generated by Django 3.2.12 on 2022-10-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_number', models.IntegerField()),
                ('pokemon_name', models.CharField(max_length=20, verbose_name='name')),
                ('pokemon_type', models.CharField(max_length=20, verbose_name='type')),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Pokemon',
            },
        ),
    ]
