# Generated by Django 4.1.2 on 2022-10-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0002_pokemon_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
            ],
            options={
                "verbose_name": "PokemonType",
                "verbose_name_plural": "PokemonTypes",
            },
        ),
    ]
