# Generated by Django 4.1.2 on 2022-10-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0003_pokemontype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="pokemon_type",
        ),
        migrations.AlterField(
            model_name="pokemontype",
            name="name",
            field=models.CharField(max_length=20, verbose_name="element_name"),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="pokemon_type",
            field=models.ManyToManyField(
                related_name="pokemon", to="pokemon.pokemontype"
            ),
        ),
    ]
