# Generated by Django 4.1.2 on 2022-10-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0004_remove_pokemon_pokemon_type_alter_pokemontype_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemontype",
            old_name="name",
            new_name="element_name",
        ),
    ]
