# Generated by Django 4.1.2 on 2022-10-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0006_alter_pokemon_height_alter_pokemon_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="description",
            field=models.TextField(
                blank=True, default="Pokemon description unavailable", null=True
            ),
        ),
    ]
